import { createLLMProvider } from '../llm/index.js';
import { runHeadAgent } from './head.js';
import type {
  MultiAgentEvent,
  MultiAgentLimits,
  MultiAgentOptions,
  MultiAgentOutcome,
  SpecialistId,
} from './types.js';

/**
 * Public entry point for the multi-agent "super agent" scan.
 *
 * Usage (code):
 *   const outcome = await runMultiAgentScan({
 *     targetUrl: 'https://target.example',
 *     scope: { mode: 'full-domain', includeSubdomains: true, excludedHosts: [], excludedPaths: [], maxRequestsPerSecond: 2 },
 *     onEvent: (e) => console.log(`[${e.kind}] ${e.message}`),
 *   });
 *
 * The caller MUST have authorization for the target (bug-bounty program,
 * pentest contract, or ownership). The swarm enforces scope, rate limits and
 * SSRF guards on every request, and all work is non-destructive.
 */

export interface MultiAgentScanRequest {
  targetUrl: string;
  scope?: {
    mode?: 'full-domain' | 'subdomain' | 'page';
    includeSubdomains?: boolean;
    excludedHosts?: string[];
    excludedPaths?: string[];
  };
  limits?: Partial<MultiAgentLimits>;
  specialists?: SpecialistId[];
  onEvent?: (e: MultiAgentEvent) => void;
  shouldContinue?: () => 'run' | 'paused' | 'cancelled';
}

export async function runMultiAgentScan(req: MultiAgentScanRequest): Promise<MultiAgentOutcome> {
  const target = new URL(req.targetUrl.trim());
  if (target.protocol !== 'http:' && target.protocol !== 'https:') {
    throw new Error('Target URL must use http(s)');
  }
  const provider = createLLMProvider();
  const opts: MultiAgentOptions = {
    targetUrl: target.toString(),
    scope: {
      mode: req.scope?.mode ?? 'subdomain',
      includeSubdomains: req.scope?.includeSubdomains ?? false,
      excludedHosts: req.scope?.excludedHosts ?? [],
      excludedPaths: req.scope?.excludedPaths ?? [],
      maxRequestsPerSecond: req.limits?.requestsPerSecond ?? 2,
    },
    provider,
    limits: req.limits,
    specialists: req.specialists,
    onEvent: req.onEvent,
    shouldContinue: req.shouldContinue,
  };
  return runHeadAgent(opts);
}

/** Render the outcome as a Markdown report (for CLI / file output). */
export function renderMarkdownReport(outcome: MultiAgentOutcome): string {
  const lines: string[] = [];
  lines.push(`# BugSeek Swarm Report — ${outcome.targetUrl}`);
  lines.push('');
  lines.push(`_Generated by the BugSeek multi-agent swarm · ${outcome.workerReports.length} specialists · ${outcome.testsRun} tests · ${(outcome.durationMs / 1000).toFixed(1)}s · ${outcome.tokensUsed.input + outcome.tokensUsed.output} tokens_`);
  lines.push('');
  lines.push('## Executive summary');
  lines.push('');
  lines.push(outcome.headSummary);
  lines.push('');
  if (outcome.findings.length === 0) {
    lines.push('## Findings');
    lines.push('');
    lines.push('No findings. The swarm found nothing worth reporting — this is not a guarantee of security.');
    lines.push('');
  } else {
    lines.push(`## Findings (${outcome.findings.length})`);
    lines.push('');
    for (const f of outcome.findings) {
      lines.push(`### [${f.severity.toUpperCase()}] ${f.title}`);
      lines.push('');
      lines.push(`- **Category:** ${f.category} · **Confidence:** ${f.confidence} · **Trap probability:** ${(f.trapProbability ?? 0).toFixed(2)}`);
      lines.push(`- **Location:** ${f.location}`);
      if (f.evidence) lines.push(`- **Evidence:** \`${f.evidence.slice(0, 300)}\``);
      lines.push('');
      lines.push(f.description);
      lines.push('');
      if (f.reproSteps?.length) {
        lines.push('**Reproduce:**');
        for (const s of f.reproSteps) lines.push(`1. ${s}`);
        lines.push('');
      }
      if (f.remediation) {
        lines.push(`**Fix:** ${f.remediation}`);
        lines.push('');
      }
    }
  }
  lines.push('## Worker reports');
  lines.push('');
  for (const r of outcome.workerReports) {
    lines.push(`- **${r.specialistName}** — ${r.summary}`);
  }
  lines.push('');
  if (outcome.errors.length > 0) {
    lines.push('## Errors');
    lines.push('');
    for (const e of outcome.errors) lines.push(`- ${e}`);
    lines.push('');
  }
  lines.push('_Authorized, in-scope, rate-limited, non-destructive testing. Verify every finding manually before reporting._');
  return lines.join('\n');
}
